version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!
    volumes:
#      - ./mysql.my.cnf:/etc/mysql/conf.d/custom.my.cnf
      - ./mysql-data:/var/lib/mysql
