version: '3'

services:
  app:
    build: .
    command:
      - "bun"
      - "--watch"
      - "src/test.js"
    volumes:
      - ./src:/home/bun/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
#      start_period: 40s

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!
    volumes:
#      - ./mysql.my.cnf:/etc/mysql/conf.d/custom.my.cnf
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
