version: '3'


services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
  db:
    image: mariadb:10.3.15-bionic
    ports:
      - "23306:3306"
    volumes:
      - ./docker/mysql.cnf:/etc/mysql/conf.d/calvin.my.cnf
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:4.7.6-standalone
    restart: always
    ports:
      - 28081:8080
    depends_on:
      - db

  redis:
    image: redis:5.0.5-stretch
    ports:
      - "26379:6379"

  crontjob:
    build:
      context: .
      dockerfile: Dockerfile.cronjob
#    volumes:
#      - .:/var/www/html
