build:
	docker-compose -f docker-compose.yml build
start:
	docker-compose -f docker-compose.yml up
api-bash:
	docker-compose -f docker-compose.yml exec api bash
db-bash:
	docker-compose -f docker-compose.yml exec db bash

