version: '3'
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
