version: '3'

services:
  api:
    build:
      context: .
      dockerfile: calvin.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ~/.ssh:/root/.ssh
  db:
    image: mongo:4.2.3-bionic
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!

#  redis:
#    image: redis:5.0.5-stretch
#    ports:
#      - "6379:6379"

#  crontjob:
#    build:
#      context: .
#      dockerfile: calvin.Dockerfile.cronjob
#    volumes:
#      - .:/var/www/html

#  node:
#    image: node:13.3.0-stretch
#    volumes:
#      - .:/var/www/html
