apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-php
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: localhost:5000/calvin/helloworld-php
          env:
            - name: TARGET
              value: "PHP Sample v1"