version: '3'
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8088:80"
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    ports:
      - "9000:9000"
