version: '3.8'

volumes:
    logs:
        driver: local

services:
    # slim app - php
    # slim-apache:
    #     image: php:8.0.1-apache-buster
    #     working_dir: /var/www
    #     command: php -S 0.0.0.0:8080 -t public
    #     environment:
    #         docker: "true"
    #     # ports:
    #     #     - 8080:8080
    #     volumes:
    #         - .:/var/www
    #         - logs:/var/www/logs
    # depends_on:
    #     - traefik



    # nginx
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "8089:80"
        depends_on:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.myproject.rule=Host(`localhost`)"
            - "traefik.http.routers.myproject.entrypoints=web"
            - "traefik.http.services.myproject.loadbalancer.server.port=80"

    # slim app - php-fpm
    # docker modify the container name that hard coded to nginx default.conf
    php-fpm: 
        build:
            context: .
            dockerfile: Dockerfile.php-fpm
        volumes:
            - ./code:/code




    # Treafik - reverse proxy
    traefik:
        image: traefik:v2.4.0-rc2
        command:
          - "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
    #    restart: always
        ports:
          - "80:80"
          - "8080:8080" # The Web UI (enabled by --api)
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock