FROM composer:2.0.8 as php-composer
COPY ./code /var/www/html
WORKDIR /var/www/html
# RUN composer global require hirak/prestissimo
RUN composer install --ignore-platform-reqs

FROM php:8.0.1-fpm-alpine3.13
# FROM php:8.0.1-zts-buster
COPY ./code /code
COPY --from=php-composer /var/www/html/vendor /code/vendor
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
