build:
	docker-compose build --no-cache
start:
	docker-compose up
api-bash:
	docker-compose exec api bash
build-dev:
	docker-compose -f docker-compose.dev.yaml build --no-cache
start-dev:
	docker-compose -f docker-compose.dev.yaml up
api-bash-dev:
	docker-compose -f docker-compose.dev.yaml exec api bash
