version: '3.8'

services:
    web:
        image: nginx:1.19.2
        volumes:
         - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
         - ./nginx-compression.conf:/etc/nginx/conf.d/compression.conf:ro
         - ./info.php:/code/info.php
        ports:
         - "8080:80"
        depends_on:
            - server-a
            - server-b
            - server-c
        # command: [nginx-debug, '-g', 'daemon off;']


    server-a:
        image: nginx:1.19.2
        volumes:
            - ./a.html:/usr/share/nginx/html/index.html

    server-b:
        image: nginx:1.19.2
        volumes:
            - ./b.html:/usr/share/nginx/html/index.html
            
    server-c:
        image: nginx:1.19.2
        volumes:
            - ./c.html:/usr/share/nginx/html/index.html
        depends_on:
            - php-fpm

    php-fpm:
        image: php:8.0-rc-fpm-buster
        volumes:
            - ./info.php:/code/info.php
            - ./php-fpm.ping.conf:/usr/local/etc/php-fpm.d/php-fpm.ping.conf
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost"]
        #     interval: 1m30s
        #     timeout: 10s
        #     retries: 3
        #     start_period: 40s
