version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    volumes:
      - ${APP_ROOT}:/var/www/html
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    ports:
      - 80:80
    depends_on:
      - db
      - cache
#    restart: always


  cronjob:
    build:
      context: .
      dockerfile: Dockerfile.cronjob
    volumes:
      - ${APP_ROOT}:/var/www/html:ro

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!
    volumes:
      - ./mysql.my.cnf:/etc/mysql/conf.d/custom.my.cnf
 #     - ./db_data:/var/lib/mysql

  # pg:
  #   image: postgres:13-rc1
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_PASSWORD=123456!
  #     - POSTGRES_USER=db_user
  #     - POSTGRES_DB=db_name

  cache:
    image: redis:5.0.5-stretch
    ports:
      - "6379:6379"

