version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    volumes:
      - ${APP_ROOT}:/var/www/html
      - ~/.ssh:/root/.ssh:ro
#    ports:
#      - 80:80
    depends_on:
      - db
      - cache
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.myproject.rule=Host(`localhost`)"
    - "traefik.http.routers.myproject.entrypoints=web"
    #- "traefik.docker.network=web"
    - "traefik.http.services.myproject.loadbalancer.server.port=80"


  cronjob:
    build:
      context: .
      dockerfile: Dockerfile.cronjob
    volumes:
      - ${APP_ROOT}:/var/www/html:ro

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!
    volumes:
      - ./mysql.my.cnf:/etc/mysql/conf.d/custom.my.cnf
 #     - ./db_data:/var/lib/mysql

  cache:
    image: redis:5.0.5-stretch
    ports:
      - "6379:6379"

  # Treafik - reverse proxy
  traefik:
    image: traefik:v2.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: always
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
