version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    volumes:
      - ../php-src:/var/www/html:ro
      - ~/.ssh:/root/.ssh
    ports:
      - 80:80

  crontjob:
    build:
      context: .
      dockerfile: Dockerfile.confjob
    volumes:
      - ../php-src:/var/www/html:ro

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_ROOT_PASSWORD=123456!
    volumes:
      - ./mysql.my.cnf:/etc/mysql/conf.d/custom.my.cnf

  redis:
    image: redis:5.0.5-stretch
    ports:
      - "6379:6379"

